/* Cronograma do Cadência Med.
 *
 * Ordem própria, montada por blocos de especialidade: os fundamentos de
 * preventiva primeiro, depois clínica, cirurgia, pediatria e GO, e dentro
 * de cada área da especialidade mais geral para a mais específica. Não
 * segue o calendário de nenhum curso preparatório, então serve para quem
 * estuda por qualquer material.
 *
 * O "id" de cada aula é fixo e é ele que fica guardado no progresso de quem
 * usa. Reordenar, renomear ou acrescentar aula não mexe no que já foi
 * marcado, desde que o id não mude. Nunca reaproveite um id para outra aula.
 */

export const CURSO = [
  { id: "epidemiologia-estudos-epidemiologicos", bloco: 1, area: "PR",
    esp: "Epidemiologia",
    titulo: "Estudos Epidemiológicos",
    topicos:
    ["Variáveis", "Testes Estatísticos", "Fases do Ensaio Clínico", "Estudos Descritivos e Metanálise"] },
  { id: "epidemiologia-epidemiologia-clinica", bloco: 1, area: "PR",
    esp: "Epidemiologia",
    titulo: "Epidemiologia Clínica",
    topicos:
    ["Verossimilhança e Testes Múltiplos", "Curva ROC e Variações no Ponto de Corte", "Medidas de Tendência Central e de Dispersão"] },
  { id: "indicadores-e-saude-coletiva-medidas-de", bloco: 2, area: "PR",
    esp: "Indicadores e saúde coletiva",
    titulo: "Medidas de Saúde Coletiva",
    topicos:
    ["Sistemas de Informação"] },
  { id: "vigilancia-vigilancia-da-saude", bloco: 3, area: "PR",
    esp: "Vigilância",
    titulo: "Vigilância da Saúde",
    topicos:
    ["Glossário de Doenças Infecciosas", "Processo Epidêmico"] },
  { id: "sus-sus-i-evolucao-historica-e", bloco: 4, area: "PR",
    esp: "SUS",
    titulo: "SUS I - Evolução Histórica e Legislação",
    topicos:
    ["Decreto 7.508"] },
  { id: "sus-sus-ii-atencao-basica-e", bloco: 4, area: "PR",
    esp: "SUS",
    titulo: "SUS II - Atenção Básica e Financiamento",
    topicos:
    ["Instrumentos de AB (Tipos de Família)", "Instrumentos de AB (Ciclo de Vida Familiar)", "Instrumentos de AB (Apgar Familiar, Practice e Firo)", "Instrumentos de AB (Escala de Coelho Savassi)", "Método SOAP", "Cofinanciamento Federal da APS"] },
  { id: "saude-do-trabalhador-e-etica-saude", bloco: 5, area: "PR",
    esp: "Saúde do trabalhador e ética",
    titulo: "Saúde do Trabalhador + Ética Médica",
    topicos:
    ["Saúde do Trabalhador: Saturnismo, Hidrargirismo, Benzenismo e Cromo"] },
  { id: "cardiologia-arritmias-i", bloco: 6, area: "CL",
    esp: "Cardiologia",
    titulo: "Arritmias I (Taquiarritmias)",
    topicos:
    ["Bloqueios de Ramo"] },
  { id: "cardiologia-arritmias-ii-pcr", bloco: 6, area: "CL",
    esp: "Cardiologia",
    titulo: "Arritmias II (Bradiarritmias) + PCR",
    topicos:
    ["Marca-passo: conceitos básicos", "Marca-passo: funcionamento do marca-passo definitivo", "Síncope"] },
  { id: "cardiologia-insuficiencia-cardiaca", bloco: 6, area: "CL",
    esp: "Cardiologia",
    titulo: "Insuficiência Cardíaca",
    topicos:
    ["Choque em pediatria", "Hipertensão pulmonar", "Cardiomiopatia dilatada", "Cardiomiopatia hipertrófica", "Cardiomiopatia restritiva", "Cardiomiopatia de estresse (takotsubo)", "Aula especial - insuficiência cardíaca aguda", "Choque: monitorização hemodinâmica e perfusional", "Choque: tratamento"] },
  { id: "cardiologia-hipertensao-arterial-sistemica-crise-hipertensiva", bloco: 6, area: "CL",
    esp: "Cardiologia",
    titulo: "Hipertensão Arterial Sistêmica; Crise Hipertensiva",
    topicos: [] },
  { id: "cardiologia-valvopatias", bloco: 6, area: "CL",
    esp: "Cardiologia",
    titulo: "Valvopatias",
    topicos: [] },
  { id: "cardiologia-doenca-arterial-coronariana-iam-e", bloco: 6, area: "CL",
    esp: "Cardiologia",
    titulo: "Doença Arterial Coronariana: IAM e Angina",
    topicos:
    ["Complicações Pós-IAM", "Pericardiopatias"] },
  { id: "pneumologia-asma-e-dpoc", bloco: 7, area: "CL",
    esp: "Pneumologia",
    titulo: "Asma e DPOC",
    topicos:
    ["Ventilação Mecânica", "Capnografia", "USG de Tórax", "Insuficiência Respiratória", "Síndrome do Desconforto Respiratório Agudo", "Provas de Função Pulmonar"] },
  { id: "pneumologia-cancer-de-pulmao-tep", bloco: 7, area: "CL",
    esp: "Pneumologia",
    titulo: "Câncer de Pulmão, TEP",
    topicos:
    ["Nódulo Pulmonar Solitário", "Embolia Gordurosa", "Tumores do Mediastino", "Pneumopatias Intersticiais Difusas", "Sarcoidose", "Hemoptise"] },
  { id: "pneumologia-pneumonia-e-complicacoes", bloco: 7, area: "CL",
    esp: "Pneumologia",
    titulo: "Pneumonia e Complicações",
    topicos:
    ["As aulas bônus são as mesmas de Tuberculose"] },
  { id: "pneumologia-tuberculose", bloco: 7, area: "CL",
    esp: "Pneumologia",
    titulo: "Tuberculose",
    topicos:
    ["Influenza", "Aspergilose", "Histoplasmose", "Paracoccidioidomicose", "Derrame pleural"] },
  { id: "nefrologia-glomerulopatias-i", bloco: 8, area: "CL",
    esp: "Nefrologia",
    titulo: "Glomerulopatias I (Nefrítica, Alterações Assintomáticas, GNRP)",
    topicos:
    ["Alport"] },
  { id: "nefrologia-glomerulopatias-ii", bloco: 8, area: "CL",
    esp: "Nefrologia",
    titulo: "Glomerulopatias II (Síndrome Nefrótica, Glomerulopatias nas Desordens Sistêmicas)",
    topicos: [] },
  { id: "nefrologia-disturbio-hidroeletrolitico", bloco: 8, area: "CL",
    esp: "Nefrologia",
    titulo: "Distúrbio Hidroeletrolítico",
    topicos:
    ["Nefrotoxicidade por Contraste", "Rabdomiólise", "Acidose Tubular Renal", "Aspectos Práticos no Tratamento da Hiponatremia", "Hipernatremia"] },
  { id: "nefrologia-insuficiencia-renal", bloco: 8, area: "CL",
    esp: "Nefrologia",
    titulo: "Insuficiência Renal",
    topicos:
    ["Terapia de Substituição Renal - HD e DP", "Terapia de Substituição Renal - Transplante"] },
  { id: "nefrologia-disturbio-acido-basico", bloco: 8, area: "CL",
    esp: "Nefrologia",
    titulo: "Distúrbio Ácido-Básico",
    topicos:
    ["Relação Delta-Delta"] },
  { id: "gastroenterologia-doencas-do-esofago", bloco: 9, area: "CL",
    esp: "Gastroenterologia",
    titulo: "Doenças do Esôfago",
    topicos:
    ["Perfuração Esofágica (Boerhaave)", "Esofagites"] },
  { id: "gastroenterologia-doencas-do-estomago", bloco: 9, area: "CL",
    esp: "Gastroenterologia",
    titulo: "Doenças do Estômago",
    topicos:
    ["Hemorragia Digestiva Alta", "GIST", "Linfoma Gástrico", "Síndrome de Zollinger-Ellison"] },
  { id: "gastroenterologia-doencas-clinicas-do-intestino", bloco: 9, area: "CL",
    esp: "Gastroenterologia",
    titulo: "Doenças Clínicas do Intestino",
    topicos:
    ["Colite Pseudomembranosa", "Síndrome do Intestino Irritável"] },
  { id: "gastroenterologia-doencas-cirurgicas-do-intestino-i", bloco: 9, area: "CL",
    esp: "Gastroenterologia",
    titulo: "Doenças Cirúrgicas do Intestino I - Vascular e Obstrução",
    topicos:
    ["Ingestão de Corpo Estranho"] },
  { id: "gastroenterologia-doencas-cirurgicas-do-intestino-ii", bloco: 9, area: "CL",
    esp: "Gastroenterologia",
    titulo: "Doenças Cirúrgicas do Intestino II - Diverticulose, Polipose, Câncer e Apendicite Aguda",
    topicos:
    ["Hemorragia Digestiva Baixa", "Tumores Carcinoides", "Tumores do Apêndice", "Câncer de Canal Anal"] },
  { id: "hepatologia-e-vias-biliares-doenca-das", bloco: 10, area: "CL",
    esp: "Hepatologia e vias biliares",
    titulo: "Doença das Vias Biliares",
    topicos:
    ["Neoplasias das Vias Biliares", "Lesão Iatrogênica da Via Biliar", "Cistos de Via Biliar", "Colangite Esclerosante Primária"] },
  { id: "hepatologia-e-vias-biliares-pancreatite-aguda", bloco: 10, area: "CL",
    esp: "Hepatologia e vias biliares",
    titulo: "Pancreatite Aguda e Crônica; Câncer de Pâncreas",
    topicos:
    ["Tumores Neuroendócrinos do Pâncreas", "Neoplasias Císticas do Pâncreas"] },
  { id: "hepatologia-e-vias-biliares-introducao-a", bloco: 10, area: "CL",
    esp: "Hepatologia e vias biliares",
    titulo: "Introdução à Hepatologia; Hepatites Virais",
    topicos:
    ["Insuficiência Hepática Aguda"] },
  { id: "hepatologia-e-vias-biliares-cirrose-e", bloco: 10, area: "CL",
    esp: "Hepatologia e vias biliares",
    titulo: "Cirrose e suas Causas",
    topicos:
    ["Hepatite Medicamentosa"] },
  { id: "hepatologia-e-vias-biliares-cirrose-e-2", bloco: 10, area: "CL",
    esp: "Hepatologia e vias biliares",
    titulo: "Cirrose e suas Complicações / Hipertensão Porta; Ascite; Encefalopatia",
    topicos:
    ["Abscesso Hepático Bacteriano", "Tumores Hepáticos Benignos", "Tumores Hepáticos Malignos"] },
  { id: "endocrinologia-tireoide", bloco: 11, area: "CL",
    esp: "Endocrinologia",
    titulo: "Tireoide",
    topicos:
    ["Hipotireoidismo Congênito"] },
  { id: "endocrinologia-doencas-da-suprarrenal", bloco: 11, area: "CL",
    esp: "Endocrinologia",
    titulo: "Doenças da Suprarrenal",
    topicos:
    ["Hipotálamo e Hipófise", "Hiperaldosteronismo Primário"] },
  { id: "endocrinologia-diabetes-mellitus", bloco: 11, area: "CL",
    esp: "Endocrinologia",
    titulo: "Diabetes Mellitus",
    topicos:
    ["Hipoglicemia", "Doença Renal do Diabetes e Retinopatia Diabética", "Neuropatia Diabética e Pé Diabético", "Dislipidemia"] },
  { id: "hematologia-anemias-i-introducao-ferropriva-doenca", bloco: 12, area: "CL",
    esp: "Hematologia",
    titulo: "Anemias I - Introdução, Ferropriva, Doença Crônica, Megaloblástica",
    topicos:
    ["Mielodisplasia", "Anemia Sideroblástica", "Anemia Aplásica"] },
  { id: "hematologia-leucemias-agudas-e-cronicas", bloco: 12, area: "CL",
    esp: "Hematologia",
    titulo: "Leucemias Agudas e Crônicas",
    topicos: [] },
  { id: "hematologia-anemia-ii-introducao-as-anemias", bloco: 12, area: "CL",
    esp: "Hematologia",
    titulo: "Anemia II - Introdução às Anemias Hemolíticas / Anemia Falciforme e Outras Hemoglobinopatias",
    topicos:
    ["Hemoglobinúria Paroxística Noturna", "Porfiria", "Talassemias"] },
  { id: "hematologia-linfomas-e-mieloma-multiplo", bloco: 12, area: "CL",
    esp: "Hematologia",
    titulo: "Linfomas e Mieloma Múltiplo",
    topicos: [] },
  { id: "hematologia-disturbios-da-hemostasia", bloco: 12, area: "CL",
    esp: "Hematologia",
    titulo: "Distúrbios da Hemostasia",
    topicos:
    ["Hemotransfusão", "Hemofilias", "Trombofilias"] },
  { id: "infectologia-aids", bloco: 13, area: "CL",
    esp: "Infectologia",
    titulo: "AIDS",
    topicos:
    ["Gastroids", "HIV na infância", "HTLV", "Citomegalovírus"] },
  { id: "infectologia-parasitoses-intestinais", bloco: 13, area: "CL",
    esp: "Infectologia",
    titulo: "Parasitoses Intestinais",
    topicos:
    ["Esquistossomose", "Toxoplasmose", "Acidente por Animais Peçonhentos"] },
  { id: "infectologia-endocardite-infecciosa-meningite", bloco: 13, area: "CL",
    esp: "Infectologia",
    titulo: "Endocardite Infecciosa / Meningite",
    topicos:
    ["Infecção Relacionada a Cateter", "Meningoencefalite Herpética", "Abscesso Cerebral", "ITU", "Sepse e Choque Séptico"] },
  { id: "infectologia-sindromes-febris", bloco: 13, area: "CL",
    esp: "Infectologia",
    titulo: "Síndromes Febris",
    topicos:
    ["Febre Tifoide", "Malária", "Febre Maculosa Brasileira", "Covid-19", "Febre do Oropouche", "Doença de Chagas", "Leishmaniose Visceral"] },
  { id: "reumatologia-introducao-a-reumatologia-artrites", bloco: 14, area: "CL",
    esp: "Reumatologia",
    titulo: "Introdução à Reumatologia + Artrites (Artrite Reumatoide, Espondiloartropatias Soronegativas)",
    topicos:
    ["AINEs e Glicocorticoides"] },
  { id: "reumatologia-gota-febre-reumatica", bloco: 14, area: "CL",
    esp: "Reumatologia",
    titulo: "Gota; Febre Reumática",
    topicos:
    ["Artrite Séptica", "Policondrite Recidivante", "Febre Familiar do Mediterrâneo", "Fibromialgia", "Artropatia por Pirofosfato de Cálcio"] },
  { id: "reumatologia-colagenoses", bloco: 14, area: "CL",
    esp: "Reumatologia",
    titulo: "Colagenoses",
    topicos:
    ["Miopatias Inflamatórias Idiopáticas", "Doença Mista do Tecido Conjuntivo", "Síndrome de Sjögren", "Amiloidoses"] },
  { id: "neurologia-neurologia-i", bloco: 15, area: "CL",
    esp: "Neurologia",
    titulo: "Neurologia I (Cefaleias, Epilepsias)",
    topicos:
    ["Tumores do SNC", "Vertigem", "Hipertensão Intracraniana", "Coma", "Trombose Venosa Cerebral", "Ataque isquêmico transitório", "Morte encefálica"] },
  { id: "neurologia-neurologia-ii", bloco: 15, area: "CL",
    esp: "Neurologia",
    titulo: "Neurologia II (Síndromes Neurológicas e AVE)",
    topicos:
    ["As aulas bônus são as mesmas de Neurologia I"] },
  { id: "neurologia-neurologia-iii", bloco: 15, area: "CL",
    esp: "Neurologia",
    titulo: "Neurologia III (Polineuropatias, Demência, Parkinson)",
    topicos:
    ["Cuidados paliativos", "Distrofias musculares", "Hipertermia maligna", "Hérnia de disco", "Doenças da placa motora"] },
  { id: "dermatologia-dermatologia-i", bloco: 16, area: "CL",
    esp: "Dermatologia",
    titulo: "Dermatologia I",
    topicos:
    ["Anafilaxia", "Piodermites", "Acne vulgar", "Mpox", "Herpes-Zóster", "Angioedema Hereditário"] },
  { id: "dermatologia-dermatologia-ii", bloco: 16, area: "CL",
    esp: "Dermatologia",
    titulo: "Dermatologia II",
    topicos:
    ["As aulas bônus são as mesmas de Dermatologia I"] },
  { id: "psiquiatria-psiquiatria-i", bloco: 17, area: "CL",
    esp: "Psiquiatria",
    titulo: "Psiquiatria I",
    topicos:
    ["Intoxicações Exógenas", "Suicídio", "Transtorno de personalidade", "Transtornos do Neurodesenvolvimento"] },
  { id: "psiquiatria-psiquiatria-ii", bloco: 17, area: "CL",
    esp: "Psiquiatria",
    titulo: "Psiquiatria II",
    topicos:
    ["As aulas bônus são as mesmas de Psiquiatria I"] },
  { id: "pre-operatorio-e-complicacoes-preparo-pre", bloco: 18, area: "CI",
    esp: "Pré-operatório e complicações",
    titulo: "Preparo Pré-Operatório, Risco Cirúrgico e Complicações em Cirurgia",
    topicos:
    ["Anestesiologia", "Fios de Sutura", "Profilaxia de TEP e TVP"] },
  { id: "trauma-trauma-i-avaliacao-inicial-e", bloco: 19, area: "CI",
    esp: "Trauma",
    titulo: "Trauma I: Avaliação Inicial e Trauma de Tórax",
    topicos:
    ["Trauma Cervical", "Trauma de Abdome - Lesões Específicas", "Lesão de Extremidade"] },
  { id: "trauma-trauma-ii-trauma-de-abdome", bloco: 19, area: "CI",
    esp: "Trauma",
    titulo: "Trauma II: Trauma de Abdome, Pelve e TCE",
    topicos: [] },
  { id: "parede-abdominal-hernias-da-parede-abdominal", bloco: 20, area: "CI",
    esp: "Parede abdominal",
    titulo: "Hérnias da Parede Abdominal",
    topicos:
    ["Abordagem Laparoscópica", "Outras Hérnias", "Hérnias na Infância"] },
  { id: "especialidades-cirurgicas-especialidade-cirurgica-parte-i", bloco: 21, area: "CI",
    esp: "Especialidades cirúrgicas",
    titulo: "Especialidade Cirúrgica - Parte I",
    topicos:
    ["Cirurgia de Cabeça e Pescoço", "Cisto Pilonidal", "Câncer de Canal Anal"] },
  { id: "especialidades-cirurgicas-especialidade-cirurgica-parte-ii", bloco: 21, area: "CI",
    esp: "Especialidades cirúrgicas",
    titulo: "Especialidade Cirúrgica - Parte II",
    topicos:
    ["As aulas bônus são as mesmas da Parte I"] },
  { id: "urologia-urologia", bloco: 22, area: "CI",
    esp: "Urologia",
    titulo: "Urologia",
    topicos:
    ["Câncer de Bexiga", "Câncer de Rim", "Disfunção Erétil", "Câncer do Testículo", "Hipogonadismo Masculino e Testosterona"] },
  { id: "ortopedia-ortopedia-i", bloco: 23, area: "CI",
    esp: "Ortopedia",
    titulo: "Ortopedia I",
    topicos:
    ["Ortopedia - Doenças periarticulares"] },
  { id: "ortopedia-ortopedia-ii", bloco: 23, area: "CI",
    esp: "Ortopedia",
    titulo: "Ortopedia II",
    topicos:
    ["As aulas bônus são as mesmas de Ortopedia I"] },
  { id: "plastica-e-queimados-queimadura-e-cirurgia", bloco: 24, area: "CI",
    esp: "Plástica e queimados",
    titulo: "Queimadura e Cirurgia Plástica",
    topicos:
    ["Suporte Nutricional"] },
  { id: "oftalmologia-oftalmologia", bloco: 25, area: "CI",
    esp: "Oftalmologia",
    titulo: "Oftalmologia",
    topicos: [] },
  { id: "cirurgia-pediatrica-cirurgia-pediatrica", bloco: 26, area: "CI",
    esp: "Cirurgia pediátrica",
    titulo: "Cirurgia Pediátrica",
    topicos: [] },
  { id: "neonatologia-neonatologia-i", bloco: 27, area: "PE",
    esp: "Neonatologia",
    titulo: "Neonatologia I",
    topicos:
    ["Triagem Neonatal", "O Exame Físico Neonatal"] },
  { id: "neonatologia-neonatologia-ii", bloco: 27, area: "PE",
    esp: "Neonatologia",
    titulo: "Neonatologia II",
    topicos:
    ["Enterocolite Necrosante"] },
  { id: "crescimento-e-nutricao-aleitamento-materno", bloco: 28, area: "PE",
    esp: "Crescimento e nutrição",
    titulo: "Aleitamento Materno",
    topicos:
    ["Alimentação Complementar"] },
  { id: "crescimento-e-nutricao-crescimento-e-desenvolvimento", bloco: 28, area: "PE",
    esp: "Crescimento e nutrição",
    titulo: "Crescimento e Desenvolvimento Normais; Puberdade Normal",
    topicos:
    ["Distúrbios Puberais"] },
  { id: "crescimento-e-nutricao-disturbios-do-crescimento", bloco: 28, area: "PE",
    esp: "Crescimento e nutrição",
    titulo: "Distúrbios do Crescimento: Desnutrição e Baixa Estatura",
    topicos:
    ["Carência de Micronutrientes", "Síndromes Genéticas"] },
  { id: "imunizacao-imunizacao", bloco: 29, area: "PE",
    esp: "Imunização",
    titulo: "Imunização",
    topicos:
    ["Profilaxia para raiva", "Profilaxia para o tétano acidental"] },
  { id: "respiratorio-pediatrico-infeccoes-respiratorias-agudas-parte", bloco: 30, area: "PE",
    esp: "Respiratório pediátrico",
    titulo: "Infecções Respiratórias Agudas - Parte I",
    topicos:
    ["Rinite Alérgica", "Estridor Crônico e Aspiração de Corpo Estranho", "Epistaxe"] },
  { id: "respiratorio-pediatrico-infeccoes-respiratorias-agudas-parte-2", bloco: 30, area: "PE",
    esp: "Respiratório pediátrico",
    titulo: "Infecções Respiratórias Agudas - Parte II",
    topicos:
    ["Fibrose Cística"] },
  { id: "gastro-e-nefro-pediatrica-diarreia-aguda", bloco: 31, area: "PE",
    esp: "Gastro e nefro pediátrica",
    titulo: "Diarreia Aguda e Desidratação na Infância",
    topicos:
    ["Constipação na Infância", "Diarreia Crônica"] },
  { id: "gastro-e-nefro-pediatrica-nefrologia-pediatrica", bloco: 31, area: "PE",
    esp: "Gastro e nefro pediátrica",
    titulo: "Nefrologia Pediátrica",
    topicos:
    ["Parada Cardiorrespiratória na Infância", "Cardiopatias Congênitas", "HAS na infância"] },
  { id: "infectologia-pediatrica-doencas-exantematicas-na-infancia", bloco: 32, area: "PE",
    esp: "Infectologia pediátrica",
    titulo: "Doenças Exantemáticas na Infância",
    topicos:
    ["Febre Sem Sinais de Localização", "Erros Inatos da Imunidade", "Tumores Abdominais na Infância", "Prevenção de Acidentes e Maus-Tratos na Infância"] },
  { id: "ginecologia-ciclo-menstrual-e-anticoncepcao", bloco: 33, area: "GO",
    esp: "Ginecologia",
    titulo: "Ciclo Menstrual e Anticoncepção",
    topicos:
    ["Síndrome Pré-Menstrual (SPM) e Síndrome Disfórica Pré-Menstrual (SDPM)", "Incongruência de Gênero"] },
  { id: "ginecologia-amenorreia-e-ovario-policistico", bloco: 33, area: "GO",
    esp: "Ginecologia",
    titulo: "Amenorreia e Ovário Policístico",
    topicos: [] },
  { id: "ginecologia-sangramento-uterino-anormal-endometriose-e", bloco: 33, area: "GO",
    esp: "Ginecologia",
    titulo: "Sangramento Uterino Anormal, Endometriose e Infertilidade",
    topicos:
    ["Infertilidade", "Dismenorreia e os Pólipos Endometriais"] },
  { id: "ginecologia-climaterio-distopia-e-incontinencia-urinaria", bloco: 33, area: "GO",
    esp: "Ginecologia",
    titulo: "Climatério, Distopia e Incontinência Urinária",
    topicos:
    ["Osteoporose", "Fístulas Genitais e Síndrome da Bexiga Dolorosa", "Anatomia em GO - Pelve Óssea, Assoalho e Períneo", "Anatomia em GO - Estruturas Pélvicas"] },
  { id: "ginecologia-doenca-das-mamas-e-ovarios", bloco: 33, area: "GO",
    esp: "Ginecologia",
    titulo: "Doença das Mamas e Ovários",
    topicos: [] },
  { id: "ginecologia-lesoes-precursoras-cancer-de-colo", bloco: 33, area: "GO",
    esp: "Ginecologia",
    titulo: "Lesões Precursoras, Câncer de Colo Uterino e Endométrio",
    topicos:
    ["Câncer de Vulva"] },
  { id: "ginecologia-ist", bloco: 33, area: "GO",
    esp: "Ginecologia",
    titulo: "IST",
    topicos:
    ["Síndrome das verrugas genitais"] },
  { id: "obstetricia-diagnostico-de-gravidez-modificacoes-do", bloco: 34, area: "GO",
    esp: "Obstetrícia",
    titulo: "Diagnóstico de Gravidez, Modificações do Organismo Materno e Pré-Natal",
    topicos:
    ["Aconselhamento Genético Pré-Natal"] },
  { id: "obstetricia-assistencia-clinica-ao-parto-e", bloco: 34, area: "GO",
    esp: "Obstetrícia",
    titulo: "Assistência Clínica ao Parto e Parto Prematuro",
    topicos:
    ["Estudo do Motor", "Mecanismo de Parto", "Cesariana"] },
  { id: "obstetricia-sangramentos-na-gravidez-parte-i", bloco: 34, area: "GO",
    esp: "Obstetrícia",
    titulo: "Sangramentos na Gravidez - Parte I",
    topicos: [] },
  { id: "obstetricia-sangramentos-na-gravidez-parte-ii", bloco: 34, area: "GO",
    esp: "Obstetrícia",
    titulo: "Sangramentos na Gravidez - Parte II e Doença Hemolítica Perinatal",
    topicos: [] },
  { id: "obstetricia-disturbios-hipertensivos-da-gestacao-diabetes", bloco: 34, area: "GO",
    esp: "Obstetrícia",
    titulo: "Distúrbios Hipertensivos da Gestação, Diabetes e Gemelaridade",
    topicos:
    ["Doenças Intercorrentes na Gestação"] },
  { id: "obstetricia-sofrimento-fetal-avaliacao-da-vitalidade", bloco: 34, area: "GO",
    esp: "Obstetrícia",
    titulo: "Sofrimento Fetal, Avaliação da Vitalidade Fetal, Fórcipe e Puerpério",
    topicos:
    ["Distúrbios do Humor e Tromboembolismo"] },
];

/* Antes o identificador era a posição na lista ("m0", "m1", ...), o que
 * quebrava tudo a cada reordenação. Esta tabela traduz o formato antigo
 * para o novo e existe só para não perder o progresso de quem já usava.
 * A posição aqui é o índice antigo; o valor é o id de hoje.
 */
export const ID_ANTIGO = [
  "ginecologia-ciclo-menstrual-e-anticoncepcao",
  "nefrologia-glomerulopatias-i",
  "ginecologia-amenorreia-e-ovario-policistico",
  "nefrologia-glomerulopatias-ii",
  "trauma-trauma-i-avaliacao-inicial-e",
  "trauma-trauma-ii-trauma-de-abdome",
  "obstetricia-diagnostico-de-gravidez-modificacoes-do",
  "nefrologia-disturbio-hidroeletrolitico",
  "nefrologia-insuficiencia-renal",
  "nefrologia-disturbio-acido-basico",
  "indicadores-e-saude-coletiva-medidas-de",
  "neonatologia-neonatologia-i",
  "epidemiologia-estudos-epidemiologicos",
  "urologia-urologia",
  "reumatologia-introducao-a-reumatologia-artrites",
  "neonatologia-neonatologia-ii",
  "reumatologia-gota-febre-reumatica",
  "epidemiologia-epidemiologia-clinica",
  "obstetricia-assistencia-clinica-ao-parto-e",
  "plastica-e-queimados-queimadura-e-cirurgia",
  "reumatologia-colagenoses",
  "vigilancia-vigilancia-da-saude",
  "cirurgia-pediatrica-cirurgia-pediatrica",
  "saude-do-trabalhador-e-etica-saude",
  "crescimento-e-nutricao-aleitamento-materno",
  "crescimento-e-nutricao-crescimento-e-desenvolvimento",
  "hematologia-anemias-i-introducao-ferropriva-doenca",
  "hematologia-leucemias-agudas-e-cronicas",
  "hematologia-anemia-ii-introducao-as-anemias",
  "hematologia-linfomas-e-mieloma-multiplo",
  "pre-operatorio-e-complicacoes-preparo-pre",
  "hematologia-disturbios-da-hemostasia",
  "parede-abdominal-hernias-da-parede-abdominal",
  "gastroenterologia-doencas-do-esofago",
  "ginecologia-sangramento-uterino-anormal-endometriose-e",
  "gastroenterologia-doencas-do-estomago",
  "gastroenterologia-doencas-clinicas-do-intestino",
  "gastroenterologia-doencas-cirurgicas-do-intestino-i",
  "obstetricia-sangramentos-na-gravidez-parte-i",
  "gastroenterologia-doencas-cirurgicas-do-intestino-ii",
  "obstetricia-sangramentos-na-gravidez-parte-ii",
  "hepatologia-e-vias-biliares-doenca-das",
  "hepatologia-e-vias-biliares-pancreatite-aguda",
  "hepatologia-e-vias-biliares-introducao-a",
  "hepatologia-e-vias-biliares-cirrose-e",
  "hepatologia-e-vias-biliares-cirrose-e-2",
  "ginecologia-climaterio-distopia-e-incontinencia-urinaria",
  "crescimento-e-nutricao-disturbios-do-crescimento",
  "cardiologia-arritmias-i",
  "imunizacao-imunizacao",
  "cardiologia-arritmias-ii-pcr",
  "cardiologia-insuficiencia-cardiaca",
  "ginecologia-doenca-das-mamas-e-ovarios",
  "cardiologia-hipertensao-arterial-sistemica-crise-hipertensiva",
  "cardiologia-valvopatias",
  "gastro-e-nefro-pediatrica-diarreia-aguda",
  "cardiologia-doenca-arterial-coronariana-iam-e",
  "sus-sus-i-evolucao-historica-e",
  "ginecologia-lesoes-precursoras-cancer-de-colo",
  "endocrinologia-tireoide",
  "sus-sus-ii-atencao-basica-e",
  "respiratorio-pediatrico-infeccoes-respiratorias-agudas-parte",
  "endocrinologia-doencas-da-suprarrenal",
  "endocrinologia-diabetes-mellitus",
  "respiratorio-pediatrico-infeccoes-respiratorias-agudas-parte-2",
  "pneumologia-asma-e-dpoc",
  "obstetricia-disturbios-hipertensivos-da-gestacao-diabetes",
  "pneumologia-cancer-de-pulmao-tep",
  "gastro-e-nefro-pediatrica-nefrologia-pediatrica",
  "pneumologia-pneumonia-e-complicacoes",
  "pneumologia-tuberculose",
  "infectologia-aids",
  "infectologia-parasitoses-intestinais",
  "obstetricia-sofrimento-fetal-avaliacao-da-vitalidade",
  "infectologia-endocardite-infecciosa-meningite",
  "infectologia-sindromes-febris",
  "ginecologia-ist",
  "neurologia-neurologia-i",
  "neurologia-neurologia-ii",
  "infectologia-pediatrica-doencas-exantematicas-na-infancia",
  "neurologia-neurologia-iii",
  "psiquiatria-psiquiatria-i",
  "psiquiatria-psiquiatria-ii",
  "oftalmologia-oftalmologia",
  "especialidades-cirurgicas-especialidade-cirurgica-parte-i",
  "especialidades-cirurgicas-especialidade-cirurgica-parte-ii",
  "dermatologia-dermatologia-i",
  "dermatologia-dermatologia-ii",
  "ortopedia-ortopedia-i",
  "ortopedia-ortopedia-ii",
];
